<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <UserSecretsId>dotnet-Ouranos.Pantheon.DataLoader.Plutus.Consumer-f021c234-2ec1-474c-8feb-175a63b0e245</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="$(MicrosoftExtensionsHostingVersion)"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\core\Ouranos.Pantheon.Core.Common\Ouranos.Pantheon.Core.Common.csproj"/>
        <ProjectReference Include="..\..\..\..\core\Ouranos.Pantheon.Core.Infra.Mongo\Ouranos.Pantheon.Core.Infra.Mongo.csproj"/>
        <ProjectReference Include="..\..\Ouranos.Pantheon.DataLoader.Plutus.Domain\Ouranos.Pantheon.DataLoader.Plutus.Domain.csproj"/>
        <ProjectReference Include="..\..\Ouranos.Pantheon.DataLoader.Plutus.Infra.RabbitMq\Ouranos.Pantheon.DataLoader.Plutus.Infra.RabbitMq.csproj"/>
        <ProjectReference Include="..\..\Ouranos.Pantheon.DataLoader.Plutus.Worker\Ouranos.Pantheon.DataLoader.Plutus.Worker.csproj"/>
    </ItemGroup>
</Project>
