<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\core\Talos.Olympus.Core.Application\Talos.Olympus.Core.Application.csproj"/>
        <ProjectReference Include="..\Talos.Olympus.Service.Plutus.Domain\Talos.Olympus.Service.Plutus.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="$(MediatrVersion)"/>
    </ItemGroup>
</Project>