<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\core\Ouranos.Pantheon.Core.Infra.RabbitMq\Ouranos.Pantheon.Core.Infra.RabbitMq.csproj"/>
        <ProjectReference Include="..\Ouranos.Pantheon.DataLoader.Plutus.Osrs.Application\Ouranos.Pantheon.DataLoader.Plutus.Osrs.Application.csproj"/>
    </ItemGroup>

</Project>
