#!/usr/bin/env sh

# Run dotnet format to check for formatting issues
dotnet format Talos.Service.Aphrodite.sln --verify-no-changes --verbosity diagnostic --severity error

# Check if dotnet format found any issues
if [ $? -ne 0 ]; then
  echo "Code is not formatted correctly. Please run 'dotnet format' to format the code." >&2
  exit 1
fi

# Allow the commit to proceed if no issues were found
exit 0
