<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RunSettingsFilePath>$(MSBuildThisFileDirectory)coverage.runsettings</RunSettingsFilePath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\tests\Ouranos.Pantheon.Tests.Utils\Ouranos.Pantheon.Tests.Utils.csproj" />
    <ProjectReference Include="..\..\..\..\src\modules\shared\Ouranos.Pantheon.Modules.Shared\Ouranos.Pantheon.Modules.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\tests\modules\shared\Ouranos.Pantheon.Modules.Shared.Contract.Tests\Ouranos.Pantheon.Modules.Shared.Contract.Tests.csproj" />
  </ItemGroup>
</Project>
