stages:
  - build_aphrodite
  - build_plutus
  - build_gateway
  - build_interface
    
before_script: 
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_aphrodite:
  stage: build_aphrodite
  image: docker:latest
  variables: 
    IMAGE_NAME: $CI_REGISTRY_IMAGE/aphrodite-service
  services:
    - docker:dind
  before_script: 
    - dotnet tool restore
  script:
    - docker build -f ./src/services/aphrodite/Dockerfile -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
    - dotnet run --project ./src/services/aphrodite/Talos.Olympus.Service.Aphrodite.API/Talos.Olympus.Service.Aphrodite.API.csproj -- schema export --output schema.graphql
    - dotnet fusion subgraph pack -p Aphrodite -s ./src/services/aphrodite/Talos.Olympus.Service.Aphrodite.API/schema.graphql
  artifacts: 
    paths:
      - Aphrodite.fsp
  only:
    - main

build_plutus:
  stage: build_plutus
  image: docker:latest
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/plutus-service
  services:
    - docker:dind
  before_script:
    - dotnet tool restore
  script:
    - docker build -f ./src/services/plutus/Dockerfile -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
    - dotnet run --project ./src/services/plutus/Talos.Olympus.Service.Plutus.API/Talos.Olympus.Service.Plutus.API.csproj -- schema export --output schema.graphql
    - dotnet fusion subgraph pack -p Plutus -s ./src/services/plutus/Talos.Olympus.Service.Plutus.API/schema.graphql
  artifacts: 
    paths:
      - Plutus.fsp
  only:
    - main

build_gateway:
  stage: build_gateway
  image: mcr.microsoft.com/dotnet/sdk:8.0
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/gateway
  before_script:
    - dotnet tool restore
  script:
    - dotnet tool restore
    - dotnet fusion compose -p ./src/gateway/Talos.Olympus.Gateway.API/Gateway -w ./subgraphs
    - docker build -f ./src/gateway/Dockerfile -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
  dependencies:
    - build_aphrodite
    - build_plutus
  only:
    - main

build_interface:
  stage: build_interface
  image: docker:stable
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/interface
  services:
    - docker:dind
  script:
    - docker build -t "$IMAGE_NAME" ./src/interface
    - docker push "$IMAGE_NAME"
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules
  only:
    - main
