stages:
  - test
  - build
  - push_images

variables:
  REGISTRY_PREFIX: "$CI_REGISTRY_IMAGE/pantheon"

.build_template: &build_template
  image: docker:stable
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -f ${DOCKERFILE_PATH} -t "${REGISTRY_PREFIX}-${IMAGE_NAME}" .
    - docker save "${REGISTRY_PREFIX}-${IMAGE_NAME}" -o "${IMAGE_NAME}.tar"
  artifacts:
    paths:
      - "${IMAGE_NAME}.tar"
  only:
    - main

dotnet_test:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: test
  script:
    - 'dotnet test'

build_gateway:
  <<: *build_template
  variables:
    IMAGE_NAME: "gateway"
    DOCKERFILE_PATH: "./src/gateway/Dockerfile"

build_interface:
  <<: *build_template
  variables:
    IMAGE_NAME: "interface"
    DOCKERFILE_PATH: "./src/interface/Dockerfile"
  cache:
    key: "$CI_COMMIT_REF_SLUG-interface"
    paths:
      - node_modules
    when: always

build_plutus_data_loader_ffxiv:
  <<: *build_template
  variables:
    IMAGE_NAME: "plutus-data-loader-ffxiv"
    DOCKERFILE_PATH: "./src/data-loaders/plutus/ffxiv/Dockerfile"

build_plutus_data_loader_osrs:
  <<: *build_template
  variables:
    IMAGE_NAME: "plutus-data-loader-osrs"
    DOCKERFILE_PATH: "./src/data-loaders/plutus/osrs/Dockerfile"

build_plutus_data_loader_stocks:
  <<: *build_template
  variables:
    IMAGE_NAME: "plutus-data-loader-stocks"
    DOCKERFILE_PATH: "./src/data-loaders/plutus/stocks/Dockerfile"

build_plutus_data_loader_consumer:
  <<: *build_template
  variables:
    IMAGE_NAME: "plutus-data-loader-consumer"
    DOCKERFILE_PATH: "./src/data-loaders/plutus/consumer/Dockerfile"

push_images:
  stage: push_images
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  dependencies:
    - build_gateway
    - build_interface
    - build_plutus_data_loader_ffxiv
    - build_plutus_data_loader_osrs
    - build_plutus_data_loader_stocks
    - build_plutus_data_loader_consumer
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - |
      for tar in *.tar; do
        IMAGE_NAME=$(basename $tar .tar)
        docker load -i "$tar"
        docker push "${REGISTRY_PREFIX}-${IMAGE_NAME}"
      done
  only:
    - main
