<Project>
    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TargetFramework>net8.0</TargetFramework>
        <Version>1.0.0</Version>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.*"/>
    </ItemGroup>

    <PropertyGroup>
        <MassTransitRabbitMQVersion>8.3.*</MassTransitRabbitMQVersion>
        <MediatrVersion>12.4.*</MediatrVersion>
        <MicrosoftConfigurationBinderVersion>8.0.*</MicrosoftConfigurationBinderVersion>
        <MicrosoftExtensionsConfigurationVersion>8.0.*</MicrosoftExtensionsConfigurationVersion>
        <MicrosoftExtensionsDependencyInjectionVersion>8.0.*</MicrosoftExtensionsDependencyInjectionVersion>
        <MicrosoftExtensionsHostingVersion>8.0.*</MicrosoftExtensionsHostingVersion>
        <MicrosoftExtensionsHttpVersion>8.0.*</MicrosoftExtensionsHttpVersion>
        <MicrosoftExtensionsOptionsConfigurationExtensionsVersion>8.0.*</MicrosoftExtensionsOptionsConfigurationExtensionsVersion>
        <MongoDriverVersion>2.27.*</MongoDriverVersion>
        <HotChocolateVersion>14.3.*</HotChocolateVersion>
        <SerilogAspNetCoreVersion>8.0.*</SerilogAspNetCoreVersion>
        <SerilogSinksConsoleVersion>6.0.*</SerilogSinksConsoleVersion>
        <SerilogSinksGrafanaLokiVersion>8.3.*</SerilogSinksGrafanaLokiVersion>
    </PropertyGroup>

    <Target Name="CopyGitHooks" AfterTargets="AfterBuild">
        <ItemGroup>
            <_CustomFiles Include="$(SolutionDir)/automation/pre-commit"/>
            <_CustomFiles Include="$(SolutionDir)/automation/pre-push"/>
        </ItemGroup>
        <Copy SourceFiles="@(_CustomFiles)" DestinationFolder="./.git/hooks"/>
    </Target>

</Project>