<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\core\Ouranos.Pantheon.Core.Application\Ouranos.Pantheon.Core.Application.csproj"/>
        <ProjectReference Include="..\..\..\..\core\Ouranos.Pantheon.Core.Domain\Ouranos.Pantheon.Core.Domain.csproj"/>
        <ProjectReference Include="..\..\..\..\services\plutus\Ouranos.Pantheon.Service.Plutus.Domain\Ouranos.Pantheon.Service.Plutus.Domain.csproj"/>
        <ProjectReference Include="..\..\Ouranos.Pantheon.DataLoader.Plutus.Domain\Ouranos.Pantheon.DataLoader.Plutus.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="$(MediatrVersion)"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder"
                          Version="$(MicrosoftConfigurationBinderVersion)"/>
    </ItemGroup>

</Project>
