<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Talos.Olympus.Core.Application\Talos.Olympus.Core.Application.csproj"/>
        <ProjectReference Include="..\Talos.Olympus.Core.Infra.Mongo\Talos.Olympus.Core.Infra.Mongo.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration"
                          Version="$(MicrosoftExtensionsConfigurationVersion)"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"
                          Version="$(MicrosoftExtensionsDependencyInjectionVersion)"/>
        <PackageReference Include="HotChocolate.AspNetCore" Version="$(HotChocolateVersion)"/>
        <PackageReference Include="HotChocolate.Data" Version="$(HotChocolateVersion)"/>
        <PackageReference Include="Serilog.AspNetCore" Version="$(SerilogAspNetCoreVersion)"/>
    </ItemGroup>

    <Target Name="CopyGitHooks" AfterTargets="AfterBuild">
        <ItemGroup>
            <_CustomFiles Include="./../automation/pre-commit"/>
            <_CustomFiles Include="./../automation/pre-push"/>
        </ItemGroup>
        <Copy SourceFiles="@(_CustomFiles)" DestinationFolder="./.git/hooks"/>
    </Target>
</Project>