<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" >
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\core\Ouranos.Pantheon.Core.API\Ouranos.Pantheon.Core.API.csproj"/>
    <ProjectReference Include="..\..\..\core\Ouranos.Pantheon.Core.Infra.OuranosMl\Ouranos.Pantheon.Core.Infra.OuranosMl.csproj" />
    <ProjectReference Include="..\..\Ouranos.Pantheon.Modules.Shared\Ouranos.Pantheon.Modules.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
      <Content Include="..\..\..\gateway\Ouranos.Pantheon.Apps.Gateway\appsettings.json" 
              Condition="Exists('..\..\..\gateway\Ouranos.Pantheon.Apps.Gateway\appsettings.json')">
          <Link>appsettings.json</Link>
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
          <CopyToPublishDirectory>Never</CopyToPublishDirectory>
      </Content>

      <Content Include="..\..\..\gateway\Ouranos.Pantheon.Apps.Gateway\appsettings.Development.json" 
              Condition="Exists('..\..\..\gateway\Ouranos.Pantheon.Apps.Gateway\appsettings.Development.json')">
          <Link>appsettings.Development.json</Link>
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
          <CopyToPublishDirectory>Never</CopyToPublishDirectory>
      </Content>
  </ItemGroup>

</Project>
