<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\core\Ouranos.Pantheon.Core.Application\Ouranos.Pantheon.Core.Application.csproj"/>
        <ProjectReference Include="..\..\Ouranos.Pantheon.DataLoader.Plutus.Application\Ouranos.Pantheon.DataLoader.Plutus.Application.csproj"/>
        <ProjectReference Include="..\..\Ouranos.Pantheon.DataLoader.Plutus.Domain\Ouranos.Pantheon.DataLoader.Plutus.Domain.csproj"/>
    </ItemGroup>

</Project>
