<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="EFCore.NamingConventions" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" >
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder"
                          />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json"
                          />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Ouranos.Pantheon.Core.Application\Ouranos.Pantheon.Core.Application.csproj"/>
        <ProjectReference Include="..\Ouranos.Pantheon.Core.Domain\Ouranos.Pantheon.Core.Domain.csproj"/>
    </ItemGroup>

</Project>
