<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="EFCore.NamingConventions" Version="$(EFCoreNamingConventionsVersion)"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="$(MicrosoftEntityFrameworkCoreDesignVersion)">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="$(MicrosoftEntityFrameworkCoreProxiesVersion)"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder"
                          Version="$(MicrosoftConfigurationBinderVersion)"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json"
                          Version="$(MicrosoftExtensionsConfigurationJsonVersion)"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="$(MicrosoftExtensionsOptionsConfigurationExtensionsVersion)"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="$(NpgsqlEntityFrameworkCorePostgreSQLVersion)"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Ouranos.Pantheon.Core.Application\Ouranos.Pantheon.Core.Application.csproj"/>
        <ProjectReference Include="..\Ouranos.Pantheon.Core.Domain\Ouranos.Pantheon.Core.Domain.csproj"/>
    </ItemGroup>

</Project>
