// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ouranos.Pantheon.Modules.Hermes.Shared.Database;

#nullable disable

namespace Ouranos.Pantheon.Hermes.Service.Infra.Postgres.Migrations
{
    [DbContext(typeof(HermesDbContext))]
    [Migration("20260502211628_AddContextWindowToModelConfigs")]
    partial class AddContextWindowToModelConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hermes")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ConversationTrait",
                b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid>("TraitsId")
                        .HasColumnType("uuid")
                        .HasColumnName("traits_id");

                    b.HasKey("ConversationId", "TraitsId")
                        .HasName("pk_conversation_trait");

                    b.HasIndex("TraitsId")
                        .HasDatabaseName("ix_conversation_trait_traits_id");

                    b.ToTable("conversation_trait", "hermes");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Hermes.Shared.Domain.Conversations.Conversation",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<Guid>("ModelConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_config_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("ModelConfigId")
                        .HasDatabaseName("ix_conversations_model_config_id");

                    b.HasIndex("PersonaId")
                        .HasDatabaseName("ix_conversations_persona_id");

                    b.ToTable("conversations", "hermes");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Hermes.Shared.Domain.Conversations.Message",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId", "SortOrder")
                        .HasDatabaseName("ix_messages_conversation_id_sort_order");

                    b.ToTable("messages", "hermes");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Hermes.Shared.Domain.Models.ModelConfig",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ContextWindow")
                        .HasColumnType("integer")
                        .HasColumnName("context_window");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_tokens");

                    b.Property<string>("ModelIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<float?>("RepeatPenalty")
                        .HasColumnType("real")
                        .HasColumnName("repeat_penalty");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<float?>("Temperature")
                        .HasColumnType("real")
                        .HasColumnName("temperature");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_model_configs");

                    b.ToTable("model_configs", "hermes");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Hermes.Shared.Domain.Personas.Persona",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Personality")
                        .HasColumnType("text")
                        .HasColumnName("personality");

                    b.Property<string>("Scenario")
                        .HasColumnType("text")
                        .HasColumnName("scenario");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_personas");

                    b.ToTable("personas", "hermes");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Hermes.Shared.Domain.Traits.Trait",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_traits");

                    b.ToTable("traits", "hermes");
                }
            );

            modelBuilder.Entity(
                "ConversationTrait",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Hermes.Shared.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_trait_conversations_conversation_id");

                    b.HasOne("Ouranos.Pantheon.Modules.Hermes.Shared.Domain.Traits.Trait", null)
                        .WithMany()
                        .HasForeignKey("TraitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_trait_traits_traits_id");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Hermes.Shared.Domain.Conversations.Conversation",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Hermes.Shared.Domain.Models.ModelConfig", "ModelConfig")
                        .WithMany()
                        .HasForeignKey("ModelConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_model_configs_model_config_id");

                    b.HasOne("Ouranos.Pantheon.Modules.Hermes.Shared.Domain.Personas.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_personas_persona_id");

                    b.Navigation("ModelConfig");

                    b.Navigation("Persona");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Hermes.Shared.Domain.Conversations.Message",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Hermes.Shared.Domain.Conversations.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversation_id");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Hermes.Shared.Domain.Conversations.Conversation",
                b => { b.Navigation("Messages"); }
            );
#pragma warning restore 612, 618
        }
    }
}
