<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\src\core\Ouranos.Pantheon.Core.Infra.OuranosMl\Ouranos.Pantheon.Core.Infra.OuranosMl.csproj"/>
        <ProjectReference Include="..\..\..\..\src\services\plutus\Ouranos.Pantheon.Service.Plutus.Application\Ouranos.Pantheon.Service.Plutus.Application.csproj"/>
        <ProjectReference Include="..\..\..\..\src\services\plutus\Ouranos.Pantheon.Service.Plutus.Infra.OuranosMl\Ouranos.Pantheon.Service.Plutus.Infra.OuranosMl.csproj"/>
    </ItemGroup>

</Project>
