// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ouranos.Pantheon.Modules.Plutus.Shared.Database;

#nullable disable

namespace Ouranos.Pantheon.Modules.Plutus.Migrations
{
    [DbContext(typeof(PlutusDbContext))]
    partial class PlutusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("plutus")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.DataLoaders.OsrsDataLoaderState",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("LastProcessed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_processed");

                    b.HasKey("Id")
                        .HasName("pk_osrs_data_loader_states");

                    b.ToTable("osrs_data_loader_states", "plutus");

                    b.HasData(new { Id = new Guid("00000000-0000-0000-0000-000000000001") });
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Forecasts.Forecast",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid")
                        .HasColumnName("symbol_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_forecasts");

                    b.HasIndex("SymbolId")
                        .HasDatabaseName("ix_forecasts_symbol_id");

                    b.ToTable("forecasts", "plutus");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Forecasts.ForecastRecord",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<int>("HorizonDays")
                        .HasColumnType("integer")
                        .HasColumnName("horizon_days");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid")
                        .HasColumnName("symbol_id");

                    b.Property<DateTimeOffset>("TargetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_forecast_records");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_forecast_records_run_id");

                    b.HasIndex("SymbolId", "GeneratedAt")
                        .HasDatabaseName("ix_forecast_records_symbol_id_generated_at");

                    b.HasIndex("TargetAt", "EvaluatedAt")
                        .HasDatabaseName("ix_forecast_records_target_at_evaluated_at");

                    b.ToTable("forecast_records", "plutus");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Forecasts.ForecastRun",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_forecast_runs");

                    b.HasIndex("GeneratedAt")
                        .HasDatabaseName("ix_forecast_runs_generated_at");

                    b.ToTable("forecast_runs", "plutus");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Markets.Market",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsForecastingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_forecasting_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_markets");

                    b.ToTable("markets", "plutus");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Positions.Position",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("LinkedBuyPositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_buy_position_id");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<int>("Side")
                        .HasColumnType("integer")
                        .HasColumnName("side");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("StrategyId")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_id");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid")
                        .HasColumnName("symbol_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("LinkedBuyPositionId")
                        .HasDatabaseName("ix_positions_linked_buy_position_id");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("ix_positions_market_id");

                    b.HasIndex("SymbolId")
                        .HasDatabaseName("ix_positions_symbol_id");

                    b.HasIndex("MarketId", "Status")
                        .HasDatabaseName("ix_positions_market_id_status");

                    b.ToTable("positions", "plutus");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Recipes.Recipe",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("ix_recipes_market_id");

                    b.ToTable("recipes", "plutus");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Signals.Signal",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid")
                        .HasColumnName("symbol_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_signals");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("ix_signals_market_id");

                    b.HasIndex("SymbolId", "Type")
                        .HasDatabaseName("ix_signals_symbol_id_type");

                    b.ToTable("signals", "plutus");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.Backtest",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("budget");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Backtest")
                        .HasColumnName("kind");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("ProgressMessage")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("progress_message");

                    b.Property<int>("ProgressPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress_percent");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_backtests");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_backtests_status");

                    b.HasIndex("StrategyId")
                        .HasDatabaseName("ix_backtests_strategy_id");

                    b.ToTable("backtests", "plutus");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.Strategy",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_strategies");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("ix_strategies_market_id");

                    b.ToTable("strategies", "plutus");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.SymbolGroups.SymbolGroup",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_symbol_groups");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("ix_symbol_groups_market_id");

                    b.ToTable("symbol_groups", "plutus");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.SymbolGroups.SymbolGroupMember",
                b =>
                {
                    b.Property<Guid>("SymbolGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("symbol_group_id");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid")
                        .HasColumnName("symbol_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("SymbolGroupId", "SymbolId")
                        .HasName("pk_symbol_group_members");

                    b.HasIndex("SymbolId")
                        .HasDatabaseName("ix_symbol_group_members_symbol_id");

                    b.ToTable("symbol_group_members", "plutus");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Symbols.Symbol",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Subcode")
                        .HasColumnType("text")
                        .HasColumnName("subcode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_symbols");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("ix_symbols_market_id");

                    b.HasIndex("Code", "Subcode", "MarketId")
                        .IsUnique()
                        .HasDatabaseName("ix_symbols_code_subcode_market_id");

                    b.ToTable("symbols", "plutus");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Trades.MarketOverviewBucket",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("average_price");

                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_start");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<int>("NumTransactions")
                        .HasColumnType("integer")
                        .HasColumnName("num_transactions");

                    b.Property<string>("TimeFrame")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_frame");

                    b.Property<decimal>("TotalSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_spent");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_market_overview_buckets");

                    b.HasIndex("MarketId", "TimeFrame")
                        .HasDatabaseName("ix_market_overview_buckets_market_id_time_frame");

                    b.ToTable("market_overview_buckets", "plutus");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Trades.MarketTradeSnapshot",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Limit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("limit");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<decimal>("MaxPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_price");

                    b.Property<decimal>("MinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("min_price");

                    b.Property<int>("NumTransactions")
                        .HasColumnType("integer")
                        .HasColumnName("num_transactions");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid")
                        .HasColumnName("symbol_id");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax");

                    b.Property<string>("TimeFrame")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_frame");

                    b.Property<decimal>("TotalSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_spent");

                    b.Property<decimal>("TotalVolume")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_volume");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_market_trade_snapshots");

                    b.HasIndex("MarketId", "TimeFrame")
                        .HasDatabaseName("ix_market_trade_snapshots_market_id_time_frame");

                    b.HasIndex("SymbolId", "TimeFrame")
                        .IsUnique()
                        .HasDatabaseName("ix_market_trade_snapshots_symbol_id_time_frame");

                    b.ToTable("market_trade_snapshots", "plutus");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Trades.Trade",
                b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid")
                        .HasColumnName("symbol_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("volume");

                    b.HasKey("Id", "Timestamp")
                        .HasName("pk_trades");

                    b.HasIndex("SymbolId")
                        .HasDatabaseName("ix_trades_symbol_id");

                    b.ToTable("trades", "plutus");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Forecasts.Forecast",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Symbols.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forecasts_symbols_symbol_id");

                    b.OwnsOne(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Forecasts.ForecastPoint",
                        "Latest",
                        b1 =>
                        {
                            b1.Property<Guid>("ForecastId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("AveragePrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("latest_average_price");

                            b1.Property<decimal>("MaxPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("latest_max_price");

                            b1.Property<decimal>("MinPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("latest_min_price");

                            b1.Property<decimal>("Volume")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("latest_volume");

                            b1.HasKey("ForecastId");

                            b1.ToTable("forecasts", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("ForecastId")
                                .HasConstraintName("fk_forecasts_forecasts_id");
                        }
                    );

                    b.OwnsMany(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Forecasts.ForecastPoint",
                        "Predictions",
                        b1 =>
                        {
                            b1.Property<Guid>("ForecastId")
                                .HasColumnType("uuid")
                                .HasColumnName("forecast_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("AveragePrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("average_price");

                            b1.Property<decimal>("MaxPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("max_price");

                            b1.Property<decimal>("MinPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("min_price");

                            b1.Property<decimal>("Volume")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("volume");

                            b1.HasKey("ForecastId", "Id")
                                .HasName("pk_forecasts_predictions");

                            b1.ToTable("forecasts_predictions", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("ForecastId")
                                .HasConstraintName("fk_forecasts_predictions_forecasts_forecast_id");
                        }
                    );

                    b.Navigation("Latest")
                        .IsRequired();

                    b.Navigation("Predictions");

                    b.Navigation("Symbol");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Forecasts.ForecastRecord",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Forecasts.ForecastRun", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forecast_records_forecast_runs_run_id");

                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Symbols.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forecast_records_symbols_symbol_id");

                    b.OwnsOne(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Forecasts.ForecastPoint",
                        "Actual",
                        b1 =>
                        {
                            b1.Property<Guid>("ForecastRecordId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("AveragePrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("actual_average_price");

                            b1.Property<decimal>("MaxPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("actual_max_price");

                            b1.Property<decimal>("MinPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("actual_min_price");

                            b1.Property<decimal>("Volume")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("actual_volume");

                            b1.HasKey("ForecastRecordId");

                            b1.ToTable("forecast_records", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("ForecastRecordId")
                                .HasConstraintName("fk_forecast_records_forecast_records_id");
                        }
                    );

                    b.OwnsOne(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Forecasts.ForecastPoint",
                        "Predicted",
                        b1 =>
                        {
                            b1.Property<Guid>("ForecastRecordId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("AveragePrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("predicted_average_price");

                            b1.Property<decimal>("MaxPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("predicted_max_price");

                            b1.Property<decimal>("MinPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("predicted_min_price");

                            b1.Property<decimal>("Volume")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("predicted_volume");

                            b1.HasKey("ForecastRecordId");

                            b1.ToTable("forecast_records", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("ForecastRecordId")
                                .HasConstraintName("fk_forecast_records_forecast_records_id");
                        }
                    );

                    b.Navigation("Actual");

                    b.Navigation("Predicted")
                        .IsRequired();

                    b.Navigation("Run");

                    b.Navigation("Symbol");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Markets.Market",
                b =>
                {
                    b.OwnsOne(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Markets.Taxes",
                        "Taxes",
                        b1 =>
                        {
                            b1.Property<Guid>("MarketId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.HasKey("MarketId");

                            b1.ToTable("markets", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("MarketId")
                                .HasConstraintName("fk_markets_markets_id");

                            b1.OwnsOne(
                                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Markets.FlatTax",
                                "Flat",
                                b2 =>
                                {
                                    b2.Property<Guid>("TaxesMarketId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Maximum")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("taxes_flat_maximum");

                                    b2.Property<decimal>("Minimum")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("taxes_flat_minimum");

                                    b2.Property<decimal>("Rate")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("taxes_flat_rate");

                                    b2.HasKey("TaxesMarketId");

                                    b2.ToTable("markets", "plutus");

                                    b2.WithOwner()
                                        .HasForeignKey("TaxesMarketId")
                                        .HasConstraintName("fk_markets_markets_id");
                                }
                            );

                            b1.Navigation("Flat");
                        }
                    );

                    b.Navigation("Taxes")
                        .IsRequired();
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Positions.Position",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Positions.Position", "LinkedBuyPosition")
                        .WithMany()
                        .HasForeignKey("LinkedBuyPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_positions_positions_linked_buy_position_id");

                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Symbols.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_symbols_symbol_id");

                    b.Navigation("LinkedBuyPosition");

                    b.Navigation("Symbol");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Recipes.Recipe",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Markets.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipes_markets_market_id");

                    b.OwnsMany(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Recipes.RecipeComponent",
                        "Inputs",
                        b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid")
                                .HasColumnName("recipe_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.Property<Guid>("SymbolId")
                                .HasColumnType("uuid")
                                .HasColumnName("symbol_id");

                            b1.HasKey("RecipeId", "Id")
                                .HasName("pk_recipes_inputs");

                            b1.ToTable("recipes_inputs", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId")
                                .HasConstraintName("fk_recipes_inputs_recipes_recipe_id");
                        }
                    );

                    b.OwnsMany(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Recipes.RecipeComponent",
                        "Outputs",
                        b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid")
                                .HasColumnName("recipe_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.Property<Guid>("SymbolId")
                                .HasColumnType("uuid")
                                .HasColumnName("symbol_id");

                            b1.HasKey("RecipeId", "Id")
                                .HasName("pk_recipes_outputs");

                            b1.ToTable("recipes_outputs", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId")
                                .HasConstraintName("fk_recipes_outputs_recipes_recipe_id");
                        }
                    );

                    b.Navigation("Inputs");

                    b.Navigation("Market");

                    b.Navigation("Outputs");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Signals.Signal",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Markets.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_signals_markets_market_id");

                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Symbols.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_signals_symbols_symbol_id");

                    b.Navigation("Market");

                    b.Navigation("Symbol");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.Backtest",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_backtests_strategies_strategy_id");

                    b.OwnsMany(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.BacktestPosition",
                        "Positions",
                        b1 =>
                        {
                            b1.Property<Guid>("BacktestId")
                                .HasColumnType("uuid")
                                .HasColumnName("backtest_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("EntryPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("entry_price");

                            b1.Property<DateTimeOffset>("EntryTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("entry_time");

                            b1.Property<decimal>("ExitPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("exit_price");

                            b1.Property<DateTimeOffset>("ExitTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("exit_time");

                            b1.Property<decimal>("ProfitLoss")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("profit_loss");

                            b1.Property<decimal>("ReturnPercent")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("return_percent");

                            b1.Property<string>("SymbolId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("symbol_id");

                            b1.Property<string>("SymbolName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("symbol_name");

                            b1.Property<decimal>("Volume")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("volume");

                            b1.HasKey("BacktestId", "Id")
                                .HasName("pk_backtest_position");

                            b1.ToTable("backtest_position", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("BacktestId")
                                .HasConstraintName("fk_backtest_position_backtests_backtest_id");
                        }
                    );

                    b.OwnsOne(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.BacktestResults",
                        "Results",
                        b1 =>
                        {
                            b1.Property<Guid>("BacktestId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("AverageTradeReturn")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("results_average_trade_return");

                            b1.Property<decimal>("BestTrade")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("results_best_trade");

                            b1.Property<decimal?>("Cagr")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("results_cagr");

                            b1.Property<decimal?>("CalmarRatio")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("results_calmar_ratio");

                            b1.Property<decimal?>("Expectancy")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("results_expectancy");

                            b1.Property<decimal>("FinalBalance")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("results_final_balance");

                            b1.Property<int>("LosingTrades")
                                .HasColumnType("integer")
                                .HasColumnName("results_losing_trades");

                            b1.Property<decimal>("MaxDrawdown")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("results_max_drawdown");

                            b1.Property<decimal>("MaxDrawdownPercent")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("results_max_drawdown_percent");

                            b1.Property<decimal?>("ProfitFactor")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("results_profit_factor");

                            b1.Property<decimal>("SharpeRatio")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("results_sharpe_ratio");

                            b1.Property<decimal?>("SortinoRatio")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("results_sortino_ratio");

                            b1.Property<decimal>("TotalReturn")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("results_total_return");

                            b1.Property<decimal>("TotalReturnPercent")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("results_total_return_percent");

                            b1.Property<int>("TotalTrades")
                                .HasColumnType("integer")
                                .HasColumnName("results_total_trades");

                            b1.Property<decimal>("WinRate")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("results_win_rate");

                            b1.Property<int>("WinningTrades")
                                .HasColumnType("integer")
                                .HasColumnName("results_winning_trades");

                            b1.Property<decimal>("WorstTrade")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("results_worst_trade");

                            b1.HasKey("BacktestId");

                            b1.ToTable("backtests", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("BacktestId")
                                .HasConstraintName("fk_backtests_backtests_id");

                            b1.OwnsOne(
                                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.TradingConfiguration",
                                "OptimizedConfiguration",
                                b2 =>
                                {
                                    b2.Property<Guid>("BacktestResultsBacktestId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<int?>("HoldPeriodDays")
                                        .HasColumnType("integer")
                                        .HasColumnName("results_optimized_configuration_hold_period_days");

                                    b2.Property<decimal?>("MaxPositionPercent")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("results_optimized_configuration_max_position_percent");

                                    b2.Property<int?>("MaxPositions")
                                        .HasColumnType("integer")
                                        .HasColumnName("results_optimized_configuration_max_positions");

                                    b2.HasKey("BacktestResultsBacktestId");

                                    b2.ToTable("backtests", "plutus");

                                    b2.WithOwner()
                                        .HasForeignKey("BacktestResultsBacktestId")
                                        .HasConstraintName("fk_backtests_backtests_id");
                                }
                            );

                            b1.OwnsOne(
                                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.ForecastMomentumConfig",
                                "OptimizedForecastMomentumConfig",
                                b2 =>
                                {
                                    b2.Property<Guid>("BacktestResultsBacktestId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<int?>("ForecastHorizonDays")
                                        .HasColumnType("integer")
                                        .HasColumnName(
                                            "results_optimized_forecast_momentum_config_forecast_horizon_days"
                                        );

                                    b2.Property<decimal?>("ForecastMovementThreshold")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName(
                                            "results_optimized_forecast_momentum_config_forecast_movement_thresh"
                                        );

                                    b2.HasKey("BacktestResultsBacktestId");

                                    b2.ToTable("backtests", "plutus");

                                    b2.WithOwner()
                                        .HasForeignKey("BacktestResultsBacktestId")
                                        .HasConstraintName("fk_backtests_backtests_id");
                                }
                            );

                            b1.OwnsOne(
                                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.MeanReversionConfig",
                                "OptimizedMeanReversionConfig",
                                b2 =>
                                {
                                    b2.Property<Guid>("BacktestResultsBacktestId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal?>("DeviationMultiplier")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("results_optimized_mean_reversion_config_deviation_multiplier");

                                    b2.Property<int?>("MeanTimeFrameValue")
                                        .HasColumnType("integer")
                                        .HasColumnName("results_optimized_mean_reversion_config_mean_time_frame_value");

                                    b2.HasKey("BacktestResultsBacktestId");

                                    b2.ToTable("backtests", "plutus");

                                    b2.WithOwner()
                                        .HasForeignKey("BacktestResultsBacktestId")
                                        .HasConstraintName("fk_backtests_backtests_id");
                                }
                            );

                            b1.OwnsOne(
                                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.RecipeArbitrageConfig",
                                "OptimizedRecipeArbitrageConfig",
                                b2 =>
                                {
                                    b2.Property<Guid>("BacktestResultsBacktestId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal?>("MinMarginPercent")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("results_optimized_recipe_arbitrage_config_min_margin_percent");

                                    b2.HasKey("BacktestResultsBacktestId");

                                    b2.ToTable("backtests", "plutus");

                                    b2.WithOwner()
                                        .HasForeignKey("BacktestResultsBacktestId")
                                        .HasConstraintName("fk_backtests_backtests_id");
                                }
                            );

                            b1.OwnsOne(
                                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.SignalWeightedConfig",
                                "OptimizedSignalWeightedConfig",
                                b2 =>
                                {
                                    b2.Property<Guid>("BacktestResultsBacktestId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal?>("BollingerBandsWeight")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName(
                                            "results_optimized_signal_weighted_config_bollinger_bands_weight"
                                        );

                                    b2.Property<decimal?>("BuyThreshold")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("results_optimized_signal_weighted_config_buy_threshold");

                                    b2.Property<decimal?>("MovingAverageCrossoverWeight")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName(
                                            "results_optimized_signal_weighted_config_moving_average_crossover_we"
                                        );

                                    b2.Property<decimal?>("PriceVelocityWeight")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName(
                                            "results_optimized_signal_weighted_config_price_velocity_weight"
                                        );

                                    b2.Property<decimal?>("RsiWeight")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("results_optimized_signal_weighted_config_rsi_weight");

                                    b2.Property<decimal?>("SellThreshold")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("results_optimized_signal_weighted_config_sell_threshold");

                                    b2.Property<decimal?>("TaxAdjustedRoiWeight")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName(
                                            "results_optimized_signal_weighted_config_tax_adjusted_roi_weight"
                                        );

                                    b2.Property<decimal?>("TrendMomentumWeight")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName(
                                            "results_optimized_signal_weighted_config_trend_momentum_weight"
                                        );

                                    b2.Property<decimal?>("VolumeAnomalyWeight")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName(
                                            "results_optimized_signal_weighted_config_volume_anomaly_weight"
                                        );

                                    b2.HasKey("BacktestResultsBacktestId");

                                    b2.ToTable("backtests", "plutus");

                                    b2.WithOwner()
                                        .HasForeignKey("BacktestResultsBacktestId")
                                        .HasConstraintName("fk_backtests_backtests_id");
                                }
                            );

                            b1.Navigation("OptimizedConfiguration");

                            b1.Navigation("OptimizedForecastMomentumConfig");

                            b1.Navigation("OptimizedMeanReversionConfig");

                            b1.Navigation("OptimizedRecipeArbitrageConfig");

                            b1.Navigation("OptimizedSignalWeightedConfig");
                        }
                    );

                    b.Navigation("Positions");

                    b.Navigation("Results");

                    b.Navigation("Strategy");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.Strategy",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Markets.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_strategies_markets_market_id");

                    b.OwnsMany(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.CompositeComponent",
                        "Components",
                        b1 =>
                        {
                            b1.Property<Guid>("StrategyId")
                                .HasColumnType("uuid")
                                .HasColumnName("strategy_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type");

                            b1.Property<decimal>("Weight")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("weight");

                            b1.HasKey("StrategyId", "Id")
                                .HasName("pk_composite_component");

                            b1.ToTable("composite_component", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("StrategyId")
                                .HasConstraintName("fk_composite_component_strategies_strategy_id");
                        }
                    );

                    b.OwnsOne(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.ForecastMomentumConfig",
                        "ForecastMomentumConfig",
                        b1 =>
                        {
                            b1.Property<Guid>("StrategyId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int?>("ForecastHorizonDays")
                                .HasColumnType("integer")
                                .HasColumnName("forecast_momentum_config_forecast_horizon_days");

                            b1.Property<decimal?>("ForecastMovementThreshold")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("forecast_momentum_config_forecast_movement_threshold");

                            b1.HasKey("StrategyId");

                            b1.ToTable("strategies", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("StrategyId")
                                .HasConstraintName("fk_strategies_strategies_id");
                        }
                    );

                    b.OwnsOne(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.MeanReversionConfig",
                        "MeanReversionConfig",
                        b1 =>
                        {
                            b1.Property<Guid>("StrategyId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal?>("DeviationMultiplier")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("mean_reversion_config_deviation_multiplier");

                            b1.Property<int?>("MeanTimeFrameValue")
                                .HasColumnType("integer")
                                .HasColumnName("mean_reversion_config_mean_time_frame_value");

                            b1.HasKey("StrategyId");

                            b1.ToTable("strategies", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("StrategyId")
                                .HasConstraintName("fk_strategies_strategies_id");
                        }
                    );

                    b.OwnsOne(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.RecipeArbitrageConfig",
                        "RecipeArbitrageConfig",
                        b1 =>
                        {
                            b1.Property<Guid>("StrategyId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal?>("MinMarginPercent")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("recipe_arbitrage_config_min_margin_percent");

                            b1.HasKey("StrategyId");

                            b1.ToTable("strategies", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("StrategyId")
                                .HasConstraintName("fk_strategies_strategies_id");
                        }
                    );

                    b.OwnsOne(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.SignalWeightedConfig",
                        "SignalWeightedConfig",
                        b1 =>
                        {
                            b1.Property<Guid>("StrategyId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal?>("BollingerBandsWeight")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("signal_weighted_config_bollinger_bands_weight");

                            b1.Property<decimal?>("BuyThreshold")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("signal_weighted_config_buy_threshold");

                            b1.Property<decimal?>("MovingAverageCrossoverWeight")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("signal_weighted_config_moving_average_crossover_weight");

                            b1.Property<decimal?>("PriceVelocityWeight")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("signal_weighted_config_price_velocity_weight");

                            b1.Property<decimal?>("RsiWeight")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("signal_weighted_config_rsi_weight");

                            b1.Property<decimal?>("SellThreshold")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("signal_weighted_config_sell_threshold");

                            b1.Property<decimal?>("TaxAdjustedRoiWeight")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("signal_weighted_config_tax_adjusted_roi_weight");

                            b1.Property<decimal?>("TrendMomentumWeight")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("signal_weighted_config_trend_momentum_weight");

                            b1.Property<decimal?>("VolumeAnomalyWeight")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("signal_weighted_config_volume_anomaly_weight");

                            b1.HasKey("StrategyId");

                            b1.ToTable("strategies", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("StrategyId")
                                .HasConstraintName("fk_strategies_strategies_id");
                        }
                    );

                    b.OwnsOne(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Strategies.TradingConfiguration",
                        "TradingConfiguration",
                        b1 =>
                        {
                            b1.Property<Guid>("StrategyId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int?>("HoldPeriodDays")
                                .HasColumnType("integer")
                                .HasColumnName("trading_configuration_hold_period_days");

                            b1.Property<decimal?>("MaxPositionPercent")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("trading_configuration_max_position_percent");

                            b1.Property<int?>("MaxPositions")
                                .HasColumnType("integer")
                                .HasColumnName("trading_configuration_max_positions");

                            b1.HasKey("StrategyId");

                            b1.ToTable("strategies", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("StrategyId")
                                .HasConstraintName("fk_strategies_strategies_id");
                        }
                    );

                    b.Navigation("Components");

                    b.Navigation("ForecastMomentumConfig");

                    b.Navigation("Market");

                    b.Navigation("MeanReversionConfig");

                    b.Navigation("RecipeArbitrageConfig");

                    b.Navigation("SignalWeightedConfig");

                    b.Navigation("TradingConfiguration")
                        .IsRequired();
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.SymbolGroups.SymbolGroup",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Markets.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symbol_groups_markets_market_id");

                    b.Navigation("Market");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.SymbolGroups.SymbolGroupMember",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.SymbolGroups.SymbolGroup", null)
                        .WithMany("Members")
                        .HasForeignKey("SymbolGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symbol_group_members_symbol_groups_symbol_group_id");

                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Symbols.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symbol_group_members_symbols_symbol_id");

                    b.Navigation("Symbol");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Symbols.Symbol",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Markets.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symbols_markets_market_id");

                    b.OwnsOne(
                        "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Symbols.AdditionalFields",
                        "AdditionalFields",
                        b1 =>
                        {
                            b1.Property<Guid>("SymbolId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Exchange")
                                .HasColumnType("text")
                                .HasColumnName("additional_fields_exchange");

                            b1.Property<string>("ExternalTradeId")
                                .HasColumnType("text")
                                .HasColumnName("additional_fields_external_trade_id");

                            b1.Property<int?>("HighAlch")
                                .HasColumnType("integer")
                                .HasColumnName("additional_fields_high_alch");

                            b1.Property<decimal?>("Limit")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("additional_fields_limit");

                            b1.Property<int?>("LowAlch")
                                .HasColumnType("integer")
                                .HasColumnName("additional_fields_low_alch");

                            b1.Property<string>("Tape")
                                .HasColumnType("text")
                                .HasColumnName("additional_fields_tape");

                            b1.HasKey("SymbolId");

                            b1.ToTable("symbols", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("SymbolId")
                                .HasConstraintName("fk_symbols_symbols_id");
                        }
                    );

                    b.Navigation("AdditionalFields")
                        .IsRequired();

                    b.Navigation("Market");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Trades.MarketOverviewBucket",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Markets.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_market_overview_buckets_markets_market_id");

                    b.Navigation("Market");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Trades.MarketTradeSnapshot",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Markets.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_market_trade_snapshots_markets_market_id");

                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Symbols.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_market_trade_snapshots_symbols_symbol_id");

                    b.Navigation("Market");

                    b.Navigation("Symbol");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Trades.Trade",
                b =>
                {
                    b.HasOne("Ouranos.Pantheon.Modules.Plutus.Shared.Domain.Symbols.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trades_symbols_symbol_id");

                    b.Navigation("Symbol");
                }
            );

            modelBuilder.Entity(
                "Ouranos.Pantheon.Modules.Plutus.Shared.Domain.SymbolGroups.SymbolGroup",
                b => { b.Navigation("Members"); }
            );
#pragma warning restore 612, 618
        }
    }
}
