<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Talos.Olympus.Core.Domain\Talos.Olympus.Core.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="$(MediatrVersion)"/>
    </ItemGroup>
</Project>