#!/usr/bin/env sh

# Run dotnet build to ensure the project builds successfully
dotnet build Talos.Service.Plutus.sln --verbosity minimal

# Check the exit status of the build command
if [ $? -ne 0 ]; then
  echo "Build failed. Aborting push." >&2
  exit 1
fi

# If build succeeds, allow the push to proceed
exit 0
