<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ouranos.Pantheon.Modules.Hestia.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Marten" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Ouranos.Pantheon.Modules.Shared\Ouranos.Pantheon.Modules.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content
      Include="..\..\..\apps\gateway\Ouranos.Pantheon.Apps.Gateway\appsettings.json"
      Condition="Exists('..\..\..\apps\gateway\Ouranos.Pantheon.Apps.Gateway\appsettings.json')"
    >
      <Link>appsettings.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>

    <Content
      Include="..\..\..\apps\gateway\Ouranos.Pantheon.Apps.Gateway\appsettings.Development.json"
      Condition="Exists('..\..\..\apps\gateway\Ouranos.Pantheon.Apps.Gateway\appsettings.Development.json')"
    >
      <Link>appsettings.Development.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
