<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR " Version="$(MediatrVersion)"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Ouranos.Pantheon.DataLoader.Plutus.Domain\Ouranos.Pantheon.DataLoader.Plutus.Domain.csproj"/>
    </ItemGroup>
</Project>
