<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HotChocolate.AspNetCore" Version="$(HotChocolateVersion)"/>
        <PackageReference Include="HotChocolate.AspNetCore.CommandLine" Version="$(HotChocolateVersion)"/>
        <PackageReference Include="HotChocolate.Data" Version="$(HotChocolateVersion)"/>
        <PackageReference Include="Serilog.Sinks.Grafana.Loki"
                          Version="$(SerilogSinksGrafanaLokiVersion)"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="$(SerilogSinksConsoleVersion)"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\core\Ouranos.Pantheon.Core.API\Ouranos.Pantheon.Core.API.csproj"/>
        <ProjectReference Include="..\Ouranos.Pantheon.Service.Plutus.Application\Ouranos.Pantheon.Service.Plutus.Application.csproj"/>
        <ProjectReference Include="..\Ouranos.Pantheon.Service.Plutus.Infra.Mongo\Ouranos.Pantheon.Service.Plutus.Infra.Mongo.csproj"/>
    </ItemGroup>

</Project>