<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HotChocolate.AspNetCore" Version="$(HotChocolateVersion)"/>
        <PackageReference Include="HotChocolate.AspNetCore.CommandLine" Version="$(HotChocolateVersion)"/>
        <PackageReference Include="HotChocolate.Data" Version="$(HotChocolateVersion)"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\core\Ouranos.Pantheon.Core.API\Ouranos.Pantheon.Core.API.csproj"/>
        <ProjectReference Include="..\..\..\core\Ouranos.Pantheon.Core.Common\Ouranos.Pantheon.Core.Common.csproj"/>
        <ProjectReference Include="..\Ouranos.Pantheon.Service.Plutus.Application\Ouranos.Pantheon.Service.Plutus.Application.csproj"/>
        <ProjectReference Include="..\Ouranos.Pantheon.Service.Plutus.Infra.Mongo\Ouranos.Pantheon.Service.Plutus.Infra.Mongo.csproj"/>
        <ProjectReference Include="..\Ouranos.Pantheon.Service.Plutus.Infra.OuranosMl\Ouranos.Pantheon.Service.Plutus.Infra.OuranosMl.csproj"/>
        <ProjectReference Include="..\Ouranos.Pantheon.Service.Plutus.Infra.Postgres\Ouranos.Pantheon.Service.Plutus.Infra.Postgres.csproj"/>
    </ItemGroup>

</Project>