<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\core\Ouranos.Pantheon.Core.Domain\Ouranos.Pantheon.Core.Domain.csproj"/>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Assistants\" />
      <Folder Include="Conversations\" />
    </ItemGroup>
</Project>