<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HotChocolate.AspNetCore" Version="$(HotChocolateVersion)"/>
        <PackageReference Include="HotChocolate.AspNetCore.CommandLine" Version="$(HotChocolateVersion)"/>
        <PackageReference Include="HotChocolate.Data" Version="$(HotChocolateVersion)"/>
        <PackageReference Include="Serilog.Sinks.Grafana.Loki"
                          Version="$(SerilogSinksGrafanaLokiVersion)"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="$(SerilogSinksConsoleVersion)"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\core\Talos.Olympus.Core.API\Talos.Olympus.Core.API.csproj"/>
        <ProjectReference Include="..\Talos.Olympus.Service.Aphrodite.Application\Talos.Olympus.Service.Aphrodite.Application.csproj"/>
        <ProjectReference Include="..\Talos.Olympus.Service.Aphrodite.Infra.Mongo\Talos.Olympus.Service.Aphrodite.Infra.Mongo.csproj"/>
        <ProjectReference Include="..\Talos.Olympus.Service.Aphrodite.Infra.TalosMl\Talos.Olympus.Service.Aphrodite.Infra.TalosMl.csproj"/>
    </ItemGroup>

</Project>