<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\src\data-loaders\plutus\Ouranos.Pantheon.DataLoader.Plutus.Application\Ouranos.Pantheon.DataLoader.Plutus.Application.csproj"/>
    </ItemGroup>

</Project>
