// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ouranos.Pantheon.Plutus.Service.Infra.Postgres;

#nullable disable

namespace Ouranos.Pantheon.Plutus.Service.Infra.Postgres.Migrations
{
    [DbContext(typeof(PlutusDbContext))]
    [Migration("20250813040737_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("plutus")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ouranos.Pantheon.Plutus.Service.Domain.Forecasts.Forecast", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("market_id");

                    b.Property<string>("SymbolId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol_id");

                    b.Property<string>("SymbolName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol_name");

                    b.Property<string>("SymbolSubcode")
                        .HasColumnType("text")
                        .HasColumnName("symbol_subcode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_forecasts");

                    b.ToTable("forecasts", "plutus");
                });

            modelBuilder.Entity("Ouranos.Pantheon.Plutus.Service.Domain.Markets.Market", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsForecastingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_forecasting_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_markets");

                    b.ToTable("markets", "plutus");
                });

            modelBuilder.Entity("Ouranos.Pantheon.Plutus.Service.Domain.Recipes.Recipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("market_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.ToTable("recipes", "plutus");
                });

            modelBuilder.Entity("Ouranos.Pantheon.Plutus.Service.Domain.SymbolGroups.SymbolGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("market_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_symbol_groups");

                    b.ToTable("symbol_groups", "plutus");
                });

            modelBuilder.Entity("Ouranos.Pantheon.Plutus.Service.Domain.Symbols.Symbol", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("market_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Subcode")
                        .HasColumnType("text")
                        .HasColumnName("subcode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_symbols");

                    b.HasIndex("Code", "Subcode", "MarketId")
                        .IsUnique()
                        .HasDatabaseName("ix_symbols_code_subcode_market_id");

                    b.ToTable("symbols", "plutus");
                });

            modelBuilder.Entity("Ouranos.Pantheon.Plutus.Service.Domain.Trades.Trade", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("SymbolId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_trades");

                    b.HasIndex("SymbolId")
                        .HasDatabaseName("ix_trades_symbol_id");

                    b.ToTable("trades", "plutus");
                });

            modelBuilder.Entity("Ouranos.Pantheon.Plutus.Service.Domain.Forecasts.Forecast", b =>
                {
                    b.OwnsOne("Ouranos.Pantheon.Plutus.Service.Domain.Forecasts.ForecastPoint", "Latest", b1 =>
                        {
                            b1.Property<string>("ForecastId")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.Property<decimal>("AveragePrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("latest_average_price");

                            b1.Property<decimal>("MaxPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("latest_max_price");

                            b1.Property<decimal>("MinPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("latest_min_price");

                            b1.Property<decimal>("Volume")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("latest_volume");

                            b1.HasKey("ForecastId");

                            b1.ToTable("forecasts", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("ForecastId")
                                .HasConstraintName("fk_forecasts_forecasts_id");
                        });

                    b.OwnsMany("Ouranos.Pantheon.Plutus.Service.Domain.Forecasts.ForecastPoint", "Predictions", b1 =>
                        {
                            b1.Property<string>("ForecastId")
                                .HasColumnType("text")
                                .HasColumnName("forecast_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("AveragePrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("average_price");

                            b1.Property<decimal>("MaxPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("max_price");

                            b1.Property<decimal>("MinPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("min_price");

                            b1.Property<decimal>("Volume")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("volume");

                            b1.HasKey("ForecastId", "Id")
                                .HasName("pk_forecasts_predictions");

                            b1.ToTable("forecasts_predictions", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("ForecastId")
                                .HasConstraintName("fk_forecasts_predictions_forecasts_forecast_id");
                        });

                    b.Navigation("Latest")
                        .IsRequired();

                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("Ouranos.Pantheon.Plutus.Service.Domain.Markets.Market", b =>
                {
                    b.OwnsOne("Ouranos.Pantheon.Plutus.Service.Domain.Markets.Taxes", "Taxes", b1 =>
                        {
                            b1.Property<string>("MarketId")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.HasKey("MarketId");

                            b1.ToTable("markets", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("MarketId")
                                .HasConstraintName("fk_markets_markets_id");

                            b1.OwnsOne("Ouranos.Pantheon.Plutus.Service.Domain.Markets.FlatTax", "Flat", b2 =>
                                {
                                    b2.Property<string>("TaxesMarketId")
                                        .HasColumnType("text")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Maximum")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("taxes_flat_maximum");

                                    b2.Property<decimal>("Minimum")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("taxes_flat_minimum");

                                    b2.Property<decimal>("Rate")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("taxes_flat_rate");

                                    b2.HasKey("TaxesMarketId");

                                    b2.ToTable("markets", "plutus");

                                    b2.WithOwner()
                                        .HasForeignKey("TaxesMarketId")
                                        .HasConstraintName("fk_markets_markets_id");
                                });

                            b1.Navigation("Flat");
                        });

                    b.Navigation("Taxes")
                        .IsRequired();
                });

            modelBuilder.Entity("Ouranos.Pantheon.Plutus.Service.Domain.Recipes.Recipe", b =>
                {
                    b.OwnsMany("Ouranos.Pantheon.Plutus.Service.Domain.Recipes.RecipeComponent", "Inputs", b1 =>
                        {
                            b1.Property<string>("RecipeId")
                                .HasColumnType("text")
                                .HasColumnName("recipe_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.Property<string>("SymbolId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("symbol_id");

                            b1.HasKey("RecipeId", "Id")
                                .HasName("pk_recipes_inputs");

                            b1.ToTable("recipes_inputs", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId")
                                .HasConstraintName("fk_recipes_inputs_recipes_recipe_id");
                        });

                    b.OwnsMany("Ouranos.Pantheon.Plutus.Service.Domain.Recipes.RecipeComponent", "Outputs", b1 =>
                        {
                            b1.Property<string>("RecipeId")
                                .HasColumnType("text")
                                .HasColumnName("recipe_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.Property<string>("SymbolId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("symbol_id");

                            b1.HasKey("RecipeId", "Id")
                                .HasName("pk_recipes_outputs");

                            b1.ToTable("recipes_outputs", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId")
                                .HasConstraintName("fk_recipes_outputs_recipes_recipe_id");
                        });

                    b.Navigation("Inputs");

                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("Ouranos.Pantheon.Plutus.Service.Domain.SymbolGroups.SymbolGroup", b =>
                {
                    b.OwnsOne("System.Collections.Generic.List<Ouranos.Pantheon.Core.Domain.Common.Id<Ouranos.Pantheon.Plutus.Service.Domain.Symbols.Symbol>>", "SymbolIds", b1 =>
                        {
                            b1.Property<string>("SymbolGroupId")
                                .HasColumnType("text");

                            b1.Property<int>("Capacity")
                                .HasColumnType("integer");

                            b1.HasKey("SymbolGroupId");

                            b1.ToTable("symbol_groups", "plutus");

                            b1.ToJson("symbol_ids");

                            b1.WithOwner()
                                .HasForeignKey("SymbolGroupId")
                                .HasConstraintName("fk_symbol_groups_symbol_groups_id");
                        });

                    b.Navigation("SymbolIds")
                        .IsRequired();
                });

            modelBuilder.Entity("Ouranos.Pantheon.Plutus.Service.Domain.Symbols.Symbol", b =>
                {
                    b.OwnsOne("Ouranos.Pantheon.Plutus.Service.Domain.Trades.AdditionalFields", "AdditionalFields", b1 =>
                        {
                            b1.Property<string>("SymbolId")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.Property<string>("Exchange")
                                .HasColumnType("text")
                                .HasColumnName("additional_fields_exchange");

                            b1.Property<string>("ExternalTradeId")
                                .HasColumnType("text")
                                .HasColumnName("additional_fields_external_trade_id");

                            b1.Property<int?>("HighAlch")
                                .HasColumnType("integer")
                                .HasColumnName("additional_fields_high_alch");

                            b1.Property<decimal?>("Limit")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("additional_fields_limit");

                            b1.Property<int?>("LowAlch")
                                .HasColumnType("integer")
                                .HasColumnName("additional_fields_low_alch");

                            b1.Property<string>("Tape")
                                .HasColumnType("text")
                                .HasColumnName("additional_fields_tape");

                            b1.HasKey("SymbolId");

                            b1.ToTable("symbols", "plutus");

                            b1.WithOwner()
                                .HasForeignKey("SymbolId")
                                .HasConstraintName("fk_symbols_symbols_id");
                        });

                    b.Navigation("AdditionalFields")
                        .IsRequired();
                });

            modelBuilder.Entity("Ouranos.Pantheon.Plutus.Service.Domain.Trades.Trade", b =>
                {
                    b.HasOne("Ouranos.Pantheon.Plutus.Service.Domain.Symbols.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trades_symbols_symbol_id");

                    b.Navigation("Symbol");
                });
#pragma warning restore 612, 618
        }
    }
}
