<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\core\Ouranos.Pantheon.Core.Infra.Mongo\Ouranos.Pantheon.Core.Infra.Mongo.csproj"/>
        <ProjectReference Include="..\Ouranos.Pantheon.DataLoader.Plutus.Consumer.Application\Ouranos.Pantheon.DataLoader.Plutus.Consumer.Application.csproj"/>
    </ItemGroup>

</Project>
