<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Ouranos.Pantheon.Core.Domain\Ouranos.Pantheon.Core.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" />
    </ItemGroup>
</Project>