#!/usr/bin/env sh

dotnet tool restore --verbosity quiet

dotnet csharpier check .
if [ $? -ne 0 ]; then
  echo "Code is not formatted correctly. Please run 'dotnet csharpier format .' to format the code." >&2
  exit 1
fi

dotnet format style --verify-no-changes --verbosity diagnostic --no-restore
if [ $? -ne 0 ]; then
  echo "Style issues found. Please run 'dotnet format style' to fix them." >&2
  exit 1
fi

dotnet format analyzers --verify-no-changes --verbosity diagnostic --no-restore
if [ $? -ne 0 ]; then
  echo "Analyzer issues found. Please run 'dotnet format analyzers' to fix them." >&2
  exit 1
fi

exit 0
