<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HotChocolate.AspNetCore" Version="$(HotChocolateVersion)"/>
        <PackageReference Include="HotChocolate.AspNetCore.CommandLine" Version="$(HotChocolateVersion)"/>
        <PackageReference Include="HotChocolate.Data" Version="$(HotChocolateVersion)"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\core\Ouranos.Pantheon.Core.API\Ouranos.Pantheon.Core.API.csproj"/>
        <ProjectReference Include="..\Ouranos.Pantheon.Hermes.Service.Application\Ouranos.Pantheon.Hermes.Service.Application.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\" />
    </ItemGroup>

</Project>