<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HotChocolate.AspNetCore" />
        <PackageReference Include="HotChocolate.AspNetCore.CommandLine" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Sinks.Grafana.Loki"
                          />
        <PackageReference Include="Serilog.Sinks.Console" />
    </ItemGroup>

    <ItemGroup>
        <None Update="Gateway.fgp">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\core\Ouranos.Pantheon.Core.API\Ouranos.Pantheon.Core.API.csproj"/>
        <ProjectReference Include="..\..\modules\hermes\Ouranos.Pantheon.Modules.Hermes\Ouranos.Pantheon.Modules.Hermes.csproj" />
        <ProjectReference Include="..\..\modules\plutus\Ouranos.Pantheon.Modules.Plutus\Ouranos.Pantheon.Modules.Plutus.csproj" />
    </ItemGroup>

</Project>